spring.application.name=laboratorio-02

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/labo-2
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Primera ejecución con base de datos vacía: dejar en always para cargar data.sql
# Luego de la primera ejecución, cambiar a never para evitar duplicados
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
